### ISSUE TITLE
Failed to render images on the pretrained srn_cars model

### ISSUE THREAD

**Issue by Yancy-lv** [ken2576/vision-nerf#11]
Failed to render images on the pretrained srn_cars model
![1](https://github.com/ken2576/vision-nerf/assets/95954197/19d765a7-3422-4226-8b08-c334f44a8881)

**Comment by wlstudy** [comment]
Hello, I have encountered the same problem. How did you solve it?

**Comment by Alptekir** [comment]
Just upgrade the PyTorch version to 1.11.0 or higher

**Comment by Lin666655** [comment]
I upgrade the pytorch version to 1.11.0,and torchvision version to 0.12.0,but this problem occur,what should i do?
![3](https://github.com/user-attachments/assets/4376d648-b310-44b8-aabd-5d9977aae54d)
