### ISSUE TITLE
A problem about cutting the Stanford automobile data set

### ISSUE THREAD

**Issue by ZhiJieChen02** [ken2576/vision-nerf#15]
Thank your great work！
When I was trying to use the Stanford Automobile Dataset to conduct experiments in real scenarios, I encountered the problem that the data set could not be cut correctly. Could you please help? I need a cut data set.

**Comment by ken2576** [comment]
I'm not sure what you mean exactly. But to get better matting, you might need to try out other object segmentation network.
Detectron2 is a good repo to start
https://github.com/facebookresearch/detectron2
