### ISSUE TITLE
Generate Multi-level Feature Maps

### ISSUE THREAD

**Issue by Yancy-lv** [ken2576/vision-nerf#16]
Hello, may I ask what is the difference between using ViT Encoder and Convolutional Decoder to generate Multi-level Feature Maps, and using PVT Encoder to generate Multi-level Feature Maps directly?

**Comment by ken2576** [comment]
Hi

I didn't specifically test PVT encoder, but the idea to use a convolutional decoder is to preserve the color information from the source images.
We found that only using the ViT encoder could cause blurriness in some areas.
