### ISSUE TITLE
question about   reproducing this paper

### ISSUE THREAD

**Issue by crazy-stycxj** [ken2576/vision-nerf#17]
when i reproduced this paper ， use the dataset  NMR  but i have question like this ：
 File "<__array_function__ internals>", line 200, in stack
  File "/home4T/cxj/anaconda3/envs/VF/lib/python3.8/site-packages/numpy/core/shape_base.py", line 460, in stack
    raise ValueError('need at least one array to stack')

i try many method，but i cant handle it  ，can you give me some suggestion，thanks

**Comment by ken2576** [comment]
It seems like you are missing the files?
Could you print out the array in question to see what happened?

**Comment by crazy-stycxj** [comment]
> It seems like you are missing the files? Could you print out the array in question to see what happened?

OK  I will check it
