### ISSUE TITLE
Weights are not available

### ISSUE THREAD

**Issue by wd-ustc-cs** [ken2576/vision-nerf#18]
Dear author, my access to your pretrained weight link has been denied recently, could you please provide me permission to download the weights? My Google account is 18098697517@163.com. I promise not to use it for any commercial purpose, very much looking forward to get your permission.
Best wishes!

**Comment by ken2576** [comment]
Hi

Sorry for the wait, but I have fixed the link.
https://drive.google.com/drive/folders/1ZnygwuNKPUdcTas28ZilzzqVC4JY_moZ?usp=sharing
