### ISSUE TITLE
ModuleNotFoundError: No module named 'configargparse'

### ISSUE THREAD

**Issue by wangniuniu123** [ken2576/vision-nerf#2]
When I use python eval_nmr.py --config [config path] to run the code always get the error:No module named 'configargparse'
So is my config file geting wrong? OR i missed some setting.

**Comment by ken2576** [comment]
Hi
Please install configargparse.
`pip install configargparse`

**Comment by wangniuniu123** [comment]
> 

![image](https://user-images.githubusercontent.com/79979044/221479480-3c7b3fbe-d4e8-4058-b719-89d6fdd509bd.png)
And I try to run the code in the anaconda, it seems a error: 'numpy.float64' object is not iterable. How to fix it?
By the way this is my config, is anything wrong, or if you could attach one example config file will be easier for users to test.
![image](https://user-images.githubusercontent.com/79979044/221479856-da978194-e35d-474d-80cf-b079a49bd69c.png)

**Comment by wangniuniu123** [comment]
And if i don't add data in  these three variables:
        self.intrinsics = []
        self.poses = []
        self.rgb_paths = []
i always get the error:ValueError: need at least one array to stack

**Comment by ken2576** [comment]
The data_path needs to be a directory.  If you are using custom data then you will have to write your own dataloader.
Please check https://github.com/ken2576/vision-nerf/blob/main/configs/train_srn_cars.txt for an example on the SRN dataset.

**Comment by wangniuniu123** [comment]
> The data_path needs to be a directory. If you are using custom data then you will have to write your own dataloader. Please check https://github.com/ken2576/vision-nerf/blob/main/configs/train_srn_cars.txt for an example on the SRN dataset.

thanks a lot
