### ISSUE TITLE
Question about training time. 

### ISSUE THREAD

**Issue by pansanity666** [ken2576/vision-nerf#7]
Hi, 
    May I ask about the specific training time and GPU number of your method on different datasets, e.g., SRN-chairs, SRN-cars,  and  NMR?
Best,

**Comment by ken2576** [comment]
Hi

We trained on 16 A100 for around 500k steps (5 days) as stated in the paper.
It is the same training time for all datasets.

**Comment by pansanity666** [comment]
> Hi
> 
> We trained on 16 A100 for around 500k steps (5 days) as stated in the paper. It is the same training time for all datasets.

Thanks
